name: Daily Counter Update

on:
  schedule:
    # Run daily at 12:00 UTC
    - cron: "0 21 * * *"
    workflow_dispatch: # Enables manual runs
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      - name: Restore dependencies
        run: dotnet restore AutoCounter/AutoCounter.csproj

      - name: Build the project
        run: dotnet build AutoCounter/AutoCounter.csproj --configuration Release


      - name: Run Counter
        run: dotnet run --project AutoCounter/AutoCounter.csproj

      - name: Commit and push changes
        run: |
          git config --global user.name "yusufcan-07"
          git config --global user.email "ulusoyyusufcan@outlook.com"
          git add counter.txt
          git commit -m "Update counter to $(cat counter.txt)"
          git push
